/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMatchupIndexRouteImport } from './routes/_app/matchup/index'
import { Route as AppFightersIndexRouteImport } from './routes/_app/fighters/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMatchupIndexRoute = AppMatchupIndexRouteImport.update({
  id: '/matchup/',
  path: '/matchup/',
  getParentRoute: () => AppRoute,
} as any)
const AppFightersIndexRoute = AppFightersIndexRouteImport.update({
  id: '/fighters/',
  path: '/fighters/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fighters/': typeof AppFightersIndexRoute
  '/matchup/': typeof AppMatchupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fighters': typeof AppFightersIndexRoute
  '/matchup': typeof AppMatchupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/fighters/': typeof AppFightersIndexRoute
  '/_app/matchup/': typeof AppMatchupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fighters/' | '/matchup/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fighters' | '/matchup'
  id: '__root__' | '/' | '/_app' | '/_app/fighters/' | '/_app/matchup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/matchup/': {
      id: '/_app/matchup/'
      path: '/matchup'
      fullPath: '/matchup/'
      preLoaderRoute: typeof AppMatchupIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fighters/': {
      id: '/_app/fighters/'
      path: '/fighters'
      fullPath: '/fighters/'
      preLoaderRoute: typeof AppFightersIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFightersIndexRoute: typeof AppFightersIndexRoute
  AppMatchupIndexRoute: typeof AppMatchupIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFightersIndexRoute: AppFightersIndexRoute,
  AppMatchupIndexRoute: AppMatchupIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
