/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchupIndexRouteImport } from './routes/matchup/index'
import { Route as FightersIndexRouteImport } from './routes/fighters/index'
import { Route as DivisionsGenderWeightClassRouteImport } from './routes/divisions.$gender.$weightClass'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupIndexRoute = MatchupIndexRouteImport.update({
  id: '/matchup/',
  path: '/matchup/',
  getParentRoute: () => rootRouteImport,
} as any)
const FightersIndexRoute = FightersIndexRouteImport.update({
  id: '/fighters/',
  path: '/fighters/',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsGenderWeightClassRoute =
  DivisionsGenderWeightClassRouteImport.update({
    id: '/divisions/$gender/$weightClass',
    path: '/divisions/$gender/$weightClass',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fighters/': typeof FightersIndexRoute
  '/matchup/': typeof MatchupIndexRoute
  '/divisions/$gender/$weightClass': typeof DivisionsGenderWeightClassRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fighters': typeof FightersIndexRoute
  '/matchup': typeof MatchupIndexRoute
  '/divisions/$gender/$weightClass': typeof DivisionsGenderWeightClassRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fighters/': typeof FightersIndexRoute
  '/matchup/': typeof MatchupIndexRoute
  '/divisions/$gender/$weightClass': typeof DivisionsGenderWeightClassRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fighters/'
    | '/matchup/'
    | '/divisions/$gender/$weightClass'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fighters' | '/matchup' | '/divisions/$gender/$weightClass'
  id:
    | '__root__'
    | '/'
    | '/fighters/'
    | '/matchup/'
    | '/divisions/$gender/$weightClass'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FightersIndexRoute: typeof FightersIndexRoute
  MatchupIndexRoute: typeof MatchupIndexRoute
  DivisionsGenderWeightClassRoute: typeof DivisionsGenderWeightClassRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchup/': {
      id: '/matchup/'
      path: '/matchup'
      fullPath: '/matchup/'
      preLoaderRoute: typeof MatchupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fighters/': {
      id: '/fighters/'
      path: '/fighters'
      fullPath: '/fighters/'
      preLoaderRoute: typeof FightersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions/$gender/$weightClass': {
      id: '/divisions/$gender/$weightClass'
      path: '/divisions/$gender/$weightClass'
      fullPath: '/divisions/$gender/$weightClass'
      preLoaderRoute: typeof DivisionsGenderWeightClassRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FightersIndexRoute: FightersIndexRoute,
  MatchupIndexRoute: MatchupIndexRoute,
  DivisionsGenderWeightClassRoute: DivisionsGenderWeightClassRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
